name: AWS EC2 Deployment Pipeline

on:
  push:
    branches: [main]

env:
  NODE_ENV: production
  AWS_REGION: ap-southeast-2  # Update your region

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 60s
          script: |
            # System setup
            sudo apt update -y
            
            # App deployment
            cd ~/app
            git pull origin main
            npm ci --production
            pm2 restart all
