name: EC2 Deployment Pipeline

on:
  push:
    branches: [main]

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Update to your region

      - name: SSH Deployment
        uses: appleboy/ssh-action@v0.5.0
        with:
          host: ${{ secrets.EC2_HOST || '3.25.116.172' }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 60s  # Increased timeout
          command_timeout: 15m
          script_stop: true
          debug: true  # Enable verbose logging
          envs: CI=true
          script: |
            set -e  # Exit immediately on error
            echo "=== Starting Deployment ==="
            
            # System updates
            sudo apt-get update -y
            
            # Navigate to app directory
            cd ~/app || { echo "App directory missing"; exit 1; }
            
            # Git operations
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            
            # Dependency management
            npm ci --production --audit=false
            
            # Process management
            pm2 flush
            pm2 restart all || pm2 start npm -- start
            
            echo "=== Deployment Complete ==="

      - name: Verify Deployment
        run: |
          echo "Checking deployment status..."
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_HOST || '3.25.116.172' }} \
            "pm2 list && curl -s localhost:3000/health"  # Update port as needed
