name: EC2 Deployment Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Deployment
        uses: appleboy/ssh-action@v0.5.0  # Verified working version
        with:
          host: "3.25.116.172"
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          script_stop: true
          script: |
            cd ~/app
            git pull origin main
            npm ci --production
            pm2 restart all || pm2 start npm -- start
