name: EC2 Deployment Pipeline

on:
  push:
    branches: [main]

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: SSH Deployment
        uses: appleboy/ssh-action@v1.2.2  # Updated to v1.2.2
        with:
          host: ${{ secrets.EC2_HOST || '3.25.116.172' }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 15m
          script_stop: true
          debug: true
          envs: CI=true
          script: |
            set -e
            echo "=== Starting Deployment ==="
            
            # System maintenance
            sudo apt-get update -y
            sudo apt-get upgrade -y --auto-remove
            
            # Application deployment
            cd ~/app || exit 1
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            
            # Dependency management
            npm ci --production --omit=dev --audit=false
            
            # Process management
            pm2 flush
            pm2 reload all --update-env || pm2 start npm --name "app" -- start
            
            echo "=== Deployment Complete ==="

      - name: Verify Deployment
        run: |
          echo "🔄 Checking deployment status..."
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_HOST || '3.25.116.172' }} \
            "pm2 list && curl -sfS http://localhost:3000/health"
