name: EC2 Deployment Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Deployment
        uses: appleboy/ssh-action@v1.0.7
        with:
          host: "3.25.116.172"  # Your EC2 IP
          username: "ubuntu"     # Ubuntu default username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          script_stop: true
          use_insecure_cipher: true  # Required for RSA compatibility
          cipher: aes128-cbc
          script: |
            # Deployment commands
            cd ~/app
            git pull origin main
            npm ci --production
            pm2 restart all || pm2 start npm -- start
