name: EC2 Deployment Pipeline

on:
  push:
    branches: [main]

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for AWS credentials
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Update region if needed

      - name: SSH Deployment
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST || '3.25.116.172' }}  # Corrected secret name
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Corrected secret name
          port: 22
          timeout: 60s
          command_timeout: 15m
          script_stop: true
          debug: true
          envs: CI=true
          script: |
            set -ex  # Enable debugging and exit on error
            echo "=== SYSTEM MAINTENANCE ==="
            sudo apt-get update -y
            sudo apt-get upgrade -y --auto-remove

            echo "=== APPLICATION DEPLOYMENT ==="
            cd ~/app || exit 1
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            echo "=== DEPENDENCY INSTALLATION ==="
            npm ci --production --omit=dev --audit=false

            echo "=== PROCESS MANAGEMENT ==="
            pm2 flush
            pm2 reload all --update-env || pm2 start npm --name "app" -- start

            echo "=== DEPLOYMENT SUCCESS ==="

      - name: Verify Deployment
        run: |
          echo "🛠️ Validating deployment health..."
          ssh -o StrictHostKeyChecking=no \
              -i ${{ secrets.SSH_PRIVATE_KEY }} \
              ubuntu@${{ secrets.EC2_HOST || '3.25.116.172' }} \
              "pm2 list && curl -sfS http://localhost:3000/health"
